import type { Metadata } from 'next';
import { PagesLayout } from '@/components/layouts';
import './globalStyles/reset.scss';
import './globalStyles/globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <PagesLayout>{children}</PagesLayout>;
}
